#=================================================================================================#
#ROLE FUNCTION - LXD Initialization without clustering                                            #
#=================================================================================================#

- name: "LXD_SERVICE/TASK_UP_SERVICE/FUNC_INIT_SELF/01 - Build init config for lxd"
  ansible.builtin.template:
    src: "{{applied_lxd_role_config.init_config.name}}.self.yml.j2"
    dest: "{{applied_lxd_role_config.role_dir}}/{{applied_lxd_role_config.init_config.target}}{{applied_lxd_role_config.init_config.name}}.yml"
  become: True
  register: check_add_config

- name: "LXD_SERVICE/TASK_UP_SERVICE/FUNC_INIT_SELF/02 - Init role from config"
  ansible.builtin.shell:
    cmd: "sudo -u {{applied_lxd_role_config.target_user}} {{applied_lxd_role_config.bin_dir}}/lxd init --preseed < {{applied_lxd_role_config.role_dir}}/{{applied_lxd_role_config.init_config.target}}{{applied_lxd_role_config.init_config.name}}.yml"
    executable: "{{applied_lxd_role_config.using_shell}}"
  when: check_add_config.changed == True