# =================================================================================================#
# ROLE TASK - UNINSTALL SCRIPT                                                                     #
# =================================================================================================#

- name: "LXD_SERVICE/TASK_UNINSTALL/01a - OS FAMILY = DEBIAN"
  ansible.builtin.include_tasks: "PLATFORMS/DEBIAN_FAMILY/function_using_{{ applied_lxd_role_config.uninstall_config.method }}.yml"
  when: ( ansible_facts.os_family == 'Debian' )

- name: "LXD_SERVICE/TASK_UNINSTALL/01b - OS FAMILY = RED HAT"
  ansible.builtin.include_tasks: "PLATFORMS/REDHAT_FAMILY/function_using_{{ applied_lxd_role_config.uninstall_config.method }}.yml"
  when: ( ansible_facts.os_family == 'RedHat' )

- name: "LXD_SERVICE/TASK_UNINSTALL/01c - OS FAMILY = ARCH"
  ansible.builtin.include_tasks: "PLATFORMS/ARCH_FAMILY/function_using_{{ applied_lxd_role_config.uninstall_config.method }}.yml"
  when: ( ansible_facts.os_family == 'Archlinux' )

- name: "LXD_SERVICE/TASK_UNINSTALL/01d - OS FAMILY = ALPINE"
  ansible.builtin.include_tasks: "PLATFORMS/ALPINE/function_using_{{ applied_lxd_role_config.uninstall_config.method }}.yml"
  when: ( ansible_facts.os_family == 'Alpine' )

- name: "LXD_SERVICE/TASK_UNINSTALL/02 - Remove role dir"
  ansible.builtin.file:
    path: "{{ applied_lxd_role_config.role_dir }}"
    state: absent
  become: true
