# =================================================================================================#
# ROLE FUNCTION - DEBIAN FAMILY - Install ZFS functionality on system                              #
# =================================================================================================#

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/01 - Get source url"
  # noqa: no-handler
  ansible.builtin.shell:
    cmd: "cat /etc/apt/sources.list | grep \"{{ ansible_distribution_release }} main\" | sed 's/\\S*/<<<&>>>/2;s/.*<<<//;s/>>>.*//'"
    executable: "{{ applied_lxd_role_config.using_shell }}"
  register: check_source_url_command
  changed_when: false
  become: true

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/02 - Get deb source for contrib non-free"
  ansible.builtin.set_fact:
    fact_source_line: "deb {{ check_source_url_command.stdout_lines[0] }} {{ ansible_distribution_release }} main contrib non-free"

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/03 - add source"
  ansible.builtin.apt_repository:
    repo: "{{ fact_source_line }}"
    state: present
  become: true

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/04 - Update with repository"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/05 - get kernel version"
  # noqa: no-handler
  ansible.builtin.shell:
    cmd: "uname -r"
    executable: "{{ applied_lxd_role_config.using_shell }}"
  register: check_kernel_version_command
  changed_when: false

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/06 - Install linux kernel headers"
  ansible.builtin.apt:
    name: "linux-headers-{{ check_kernel_version_command.stdout_lines[0] }}"
    state: latest
  become: true

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/07 - Install ZFS through apt"
  ansible.builtin.apt:
    name: "zfsutils-linux"
    state: latest
  become: true

- name: "LXD_SERVICE/TASK_INSTALL/DEBIAN_FAMILY/ZFS/08 - Load ZFS module into system"
  community.general.modprobe:
    name: zfs
    state: present
