#=================================================================================================#
#ROLE FUNCTION - Provision a dir storage pool located entirely within project directory in rootfs #
#=================================================================================================#

- name: "LXD_SERVICE/TASK_INIT/FUNC_EASY_DIR/01 - Make LXD easy_dir directory"
  ansible.builtin.file:
    path: "{{applied_lxd_role_config.role_dir}}/pools/{{input_store.name}}"
    state: directory
  become: True
  register: check_add_storage

- name: "LXD_SERVICE/TASK_INIT/FUNC_EASY_DIR/02 - Build storage pool for LXD"
  ansible.builtin.shell:
    cmd: "sudo -u {{applied_lxd_role_config.target_user}} {{applied_lxd_role_config.bin_dir}}/lxc storage create {{input_store.name}} dir source={{applied_lxd_role_config.role_dir}}/pools/{{input_store.name}}"
    executable: "{{applied_lxd_role_config.using_shell}}"
  when: check_add_storage.changed == True