# =================================================================================================#
# ROLE FUNCTION - Provision a dir storage pool located entirely within project directory in rootfs #
# =================================================================================================#

- name: "LXD_SERVICE/TASK_INIT/FUNC_ROLE_DIR/01 - Where's our storage directory located?"
  ansible.builtin.set_fact:
    fact_pool_target_dir: "{{ applied_lxd_role_config.role_dir }}/pools/dir/{{ input_store.name }}"

- name: "LXD_SERVICE/TASK_INIT/FUNC_ROLE_DIR/02 - Make LXD role_dir directory"
  ansible.builtin.file:
    path: "{{ fact_pool_target_dir }}"
    state: directory
    mode: "0755"
  become: true
