# =================================================================================================#
# ROLE MODE - INITIALIZE STORAGE                                                                   #
# =================================================================================================#

- name: "LXD_SERVICE/TASK_UP_STORAGE/01 - Make LXD Environment Base"
  ansible.builtin.file:
    path: "{{ applied_lxd_role_config.role_dir }}"
    state: directory
    mode: "0755"
  become: true

- name: "LXD_SERVICE/TASK_UP_STORAGE/02 - Add all role_dirs"
  ansible.builtin.include_tasks: func_role_dir.yml
  vars:
    input_store: "{{ current_store }}"
  with_items: "{{ applied_lxd_role_config.storage_pools | selectattr('driver', 'equalto', 'role_dir') }}"
  loop_control:
    loop_var: current_store

- name: "LXD_SERVICE/TASK_UP_STORAGE/03 - Add all role_btrfs"
  ansible.builtin.include_tasks: func_role_btrfs.yml
  vars:
    input_store: "{{ current_store }}"
  with_items: "{{ applied_lxd_role_config.storage_pools | selectattr('driver', 'equalto', 'role_btrfs') }}"
  loop_control:
    loop_var: current_store

- name: "LXD_SERVICE/TASK_UP_STORAGE/04 - Add all role_zfs"
  ansible.builtin.include_tasks: func_role_zfs.yml
  vars:
    input_store: "{{ current_store }}"
  with_items: "{{ applied_lxd_role_config.storage_pools | selectattr('driver', 'equalto', 'role_zfs') }}"
  loop_control:
    loop_var: current_store
