# =================================================================================================#
# ROLE FUNCTION - Storage Objects are a part of one host                                           #
# =================================================================================================#

- name: "LXD_SERVICE/TASK_CLEAN/FUNCTION_SINGLE_LOCATION_HANDLER/01 - Bring down storage by itself if not clustered"
  ansible.builtin.shell:
    cmd: "sudo -u {{ applied_lxd_role_config.target_user }} {{ applied_lxd_role_config.bin_dir }}/lxc storage delete {{ current_storage.name }}"
    executable: "{{ applied_lxd_role_config.using_shell }}"
  changed_when: false
  with_items: "{{ input_storage_items }}"
  loop_control:
    loop_var: current_storage
  when: ( not ( input_is_cluster | default(false) ) )

- name: "LXD_SERVICE/TASK_CLEAN/FUNCTION_SINGLE_LOCATION_HANDLER/02 - Remove Storage - DIR"
  ansible.builtin.include_tasks: "RM_TYPE/func_rm_storage_dir.yml"
  vars:
    input_storage: "{{ current_storage }}"
  with_items: "{{ input_storage_items | selectattr('driver', 'equalto', 'dir') }}"
  loop_control:
    loop_var: current_storage

- name: "LXD_SERVICE/TASK_CLEAN/FUNCTION_SINGLE_LOCATION_HANDLER/03 - Remove Storage - BTRFS"
  ansible.builtin.include_tasks: "RM_TYPE/func_rm_storage_btrfs.yml"
  vars:
    input_storage: "{{ current_storage }}"
  with_items: "{{ input_storage_items | selectattr('driver', 'equalto', 'btrfs') }}"
  loop_control:
    loop_var: current_storage

- name: "LXD_SERVICE/TASK_CLEAN/FUNCTION_SINGLE_LOCATION_HANDLER/04 - Remove Storage - ZFS"
  ansible.builtin.include_tasks: "RM_TYPE/func_rm_storage_Zfs.yml"
  vars:
    input_storage: "{{ current_storage }}"
  with_items: "{{ input_storage_items | selectattr('driver', 'equalto', 'zfs') }}"
  loop_control:
    loop_var: current_storage

# -----
# TO_DO: add more ways to remove storage
# -----
